name: 'Build Layer to CloudFormation'
on:
  push:
    branches:
        - 1.1.0-geothings
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 'Installing Serverless'
        run: npm install -g serverless
      - name: 'Sign in to AWS'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: 'Build GeoLambda'
        run: |
          mkdir ~/geolambda
          cp serverless.yml ~/geolambda
          docker build -t geolambda .
          docker run --rm -v ~/geolambda:/home/geolambda geolambda package.sh
      - name: 'Deploy Geolambda'
        run: |
          sls deploy --stage 1.1.0-geothings